#define AMBIENT_SOUND_LAVA 1
#define AMBIENT_SOUND_WATER 2
#define TOTAL_AMBIENT_SOUNDS 2 //KEEP THIS UP TO DATE!

#define AMBIENCE_SWEEP_TIME 5 SECONDS

#define MAX_AMBIENCE_RANGE 5

#define AMBIENCE_FALLOFF_DISTANCE 3
#define AMBIENCE_FALLOFF_EXPONENT 1
