#define AMBIENT_SOUND_LAVA 1
#define AMBIENT_SOUND_WATER 2
#define AMBIENT_SOUND_HEARTBEAT 3
#define AMBIENT_SOUND_SPARKS 4
#define AMBIENT_SOUND_THUNDER 5
#define AMBIENT_SOUND_STATION_CREAK 6
#define AMBIENT_SOUND_FIRE 7
#define AMBIENT_SOUND_CRUNCHY_SERVER 8
#define AMBIENT_SOUND_SERVER 9
#define AMBIENT_SOUND_VENDING 10

#define TOTAL_AMBIENT_SOUNDS 10 //KEEP THIS UP TO DATE!


#define AMBIENCE_SWEEP_TIME 3 SECONDS

#define AMBIENCE_QUEUE_TIME 4 SECONDS

#define MAX_AMBIENCE_RANGE 5

#define AMBIENCE_FALLOFF_DISTANCE 2
#define AMBIENCE_FALLOFF_EXPONENT 1

#define SHIP_AMBIENCE_VOLUME 15
