#define PAIN_CRIT_STATE_NONE 0
#define PAIN_CRIT_STATE_CRAWLING 1
#define PAIN_CRIT_STATE_INCAPACITATED 2
#define PAIN_CRIT_STATE_UNCONSCIOUS 3

#define PAIN_MESSAGE_THRESHOLD 40
#define PAIN_SCREAM_THRESHOLD 50
#define PAIN_SCREAM_TRIGGER_THRESHOLD 10
#define PAIN_SCREAM_TRIGGER_MULTIPLIER 2

#define PAIN_SLOWDOWN_THRESHOLD 50
#define PAIN_SLOWDOWN_DIVISOR 100

#define PAIN_MAXIMUM 300

#define BLUNT_WEAPON_PAIN_MULTIPLIER 2.1
#define SHARP_WEAPON_PAIN_MULTIPLIER 1.6

#define RIOT_BULLETS_PAIN_MULTIPLIER 4
#define SHARP_BULLETS_PAIN_MULTIPLIER 2

#define PAIN "pain"
