//Could be bitflags, but that would require a good amount of translations, which eh, either way works for me
#define TAG_COMBAT "combat"
#define TAG_SPOOKY "spooky"
#define TAG_DESTRUCTIVE "destructive"
#define TAG_COMMUNAL "communal"
#define TAG_TARGETED "targeted"
#define TAG_POSITIVE "positive"
#define TAG_OVERMAP "overmap"
#define TAG_SPACE "space"
#define TAG_PLANETARY "planetary"

#define EVENT_TRACK_MUNDANE "Mundane"
#define EVENT_TRACK_MODERATE "Moderate"
#define EVENT_TRACK_MAJOR "Major"
#define EVENT_TRACK_ROLESET "Roleset"
#define EVENT_TRACK_OBJECTIVES "Objectives"

#define ALL_EVENTS "All"
#define UNCATEGORIZED_EVENTS "Uncategorized"

#define STORYTELLER_WAIT_TIME 20 SECONDS

#define EVENT_POINT_GAINED_PER_SECOND 0.05

#define TRACK_FAIL_POINT_PENALTY_MULTIPLIER 0.5

#define GAMEMODE_PANEL_MAIN "Main"
#define GAMEMODE_PANEL_VARIABLES "Variables"

#define MUNDANE_POINT_THRESHOLD 25
#define MODERATE_POINT_THRESHOLD 50
#define MAJOR_POINT_THRESHOLD 90
#define ROLESET_POINT_THRESHOLD 120
#define OBJECTIVES_POINT_THRESHOLD 130

#define MUNDANE_MIN_POP 4
#define MODERATE_MIN_POP 6
#define MAJOR_MIN_POP 10
#define ROLESET_MIN_POP 10
#define OBJECTIVES_MIN_POP 10

#define EVENT_TRACKS list(EVENT_TRACK_MUNDANE, EVENT_TRACK_MODERATE, EVENT_TRACK_MAJOR, EVENT_TRACK_ROLESET, EVENT_TRACK_OBJECTIVES)
#define EVENT_PANEL_TRACKS list(EVENT_TRACK_MUNDANE, EVENT_TRACK_MODERATE, EVENT_TRACK_MAJOR, EVENT_TRACK_ROLESET, EVENT_TRACK_OBJECTIVES, UNCATEGORIZED_EVENTS, ALL_EVENTS)
