#define TAG_COMBAT 1
#define TAG_SPOOKY 2
#define TAG_DESTRUCTIVE 3
#define TAG_COMMUNAL 4
#define TAG_TARGETED 5
#define TAG_POSITIVE 6
#define TAG_OVERMAP 7
#define TAG_SPACE 8
#define TAG_PLANETARY 9

#define EVENT_TRACK_MUNDANE 1
#define EVENT_TRACK_MODERATE 2
#define EVENT_TRACK_MAJOR 3
#define EVENT_TRACK_ROLESET 4
#define EVENT_TRACK_OBJECTIVES 5
